-- +migrate Up
CREATE TABLE order_transactions (
  id VARCHAR(36) PRIMARY KEY,
  notification_id INT(4),
  customer_id VARCHAR(36) NOT NULL,
  mitra_id VARCHAR(36) NOT NULL,
  service_id INT NOT NULL,
  sub_service_id INT NOT NULL,
  order_radius INT,
  customer_name VARCHAR(255),
  order_type ENUM('now', 'coming soon', 'repeat'),
  mitra_gender ENUM('male', 'female'),
  order_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  order_progress_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  order_blast_time DATETIME,
  order_time_temp DATETIME DEFAULT CURRENT_TIMESTAMP,
  order_origin_soon_time VARCHAR(255),
  order_timestamp VARCHAR(255),
  address VARCHAR(255),
  canceled_user ENUM('customer', 'mitra', 'admin', 'superadmin'),
  canceled_reason TEXT,
  order_note VARCHAR(255),
  payment_type ENUM('tunai', 'balance', 'debit', 'credit'),
  payment VARCHAR(255),
  order_status ENUM('WAITING_PAYMENT', 'WAIT_SCHEDULE', 'OTW', 'ON_PROGRESS', 'FINISH', 'CANCELED','CANCELED_CANT_FIND_MITRA','CANCELED_BY_SYSTEM', 'CANCELED_VOID' , 'CANCELED_VOID_BY_SYSTEM', 'CANCELED_REFUND', 'CANCELED_LATE_PAYMENT', 'CANCELED_FAILED_PAYMENT', 'FINDING_MITRA', 'PROCESSING_PAYMENT', 'WAITING_FOR_SELECTED_MITRA'),
  void_status ENUM('VOID_PENDING', 'VOID_SUCCEEDED', 'VOID_FAILED'),
  void_description TEXT,
  id_transaction VARCHAR(255),
  is_rated ENUM('0', '1'),
  is_rated_mitra ENUM('0', '1'),
  rated DOUBLE,
  rated_customer DOUBLE,
  is_mitra_online ENUM('0', '1'),
  is_customer_online ENUM('0', '1'),
  chat_mitra_id TEXT,
  chat_customer_id TEXT,
  call_mitra_id TEXT,
  call_customer_id TEXT,
  coordinate_receiver_id TEXT,
  is_additional ENUM('true', 'false'),
  order_count_additional INT,
  order_time_additional DATETIME,
  gross_amount_additional INT,
  gross_amount INT,
  gross_amount_mitra INT,
  gross_amount_company INT,
  gross_amount_company_after_deduction INT,
  total_order_repeat INT,
  total_waiting_repeat INT,
  total_done_repeat INT,
  is_paid_customer ENUM('0', '1'),
  private_key_rsa VARCHAR(255),
  public_key_rsa VARCHAR(255),
  public_key_mitra BIGINT,
  public_key_customer BIGINT,
  mitra_secret BIGINT,
  customer_secret BIGINT,
  timezone_code VARCHAR(255),
  customer_latitude DOUBLE,
  customer_longitude DOUBLE,
  mitra_latitude DOUBLE,
  mitra_longitude DOUBLE,
  payment_id_pay VARCHAR(100),
  order_id_pay VARCHAR(100),
  customer_id_pay VARCHAR(19),
  amount_pay VARCHAR(100),
  payment_option VARCHAR(100),
  pending_amount VARCHAR(100),
  status VARCHAR(30),
  is_live ENUM('true', 'false'),
  access_token TEXT,
  expire_time VARCHAR(255),
  expiry_date VARCHAR(255),
  account_number_va VARCHAR(25),
  mobile_ewallet VARCHAR(20),
  checkout_url_ewallet TEXT,
  web_url_ewallet TEXT,
  qr_string TEXT,
  qr_code TEXT,
  va_id VARCHAR(255),
  owner_id VARCHAR(255),
  external_id VARCHAR(255),
  bank_code VARCHAR(255),
  merchant_code VARCHAR(255),
  name VARCHAR(255),
  account_number VARCHAR(255),
  expected_amount VARCHAR(255),
  is_closed VARCHAR(255),
  expiration_date VARCHAR(255),
  xendit_id VARCHAR(255),
  is_single_use ENUM('0', '1'),
  currency VARCHAR(255),
  xendit_status VARCHAR(255),
  shared_prime INT,
  expiration_time VARCHAR(255),
  offer_expired_job_id VARCHAR(255),
  offer_selected_job_id VARCHAR(255),
  on_progress_job_id VARCHAR(36),
  ewallet_notify_job_id VARCHAR(255),
  direction_response TEXT,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL,
  FOREIGN KEY (customer_id) REFERENCES users(id),
  FOREIGN KEY (mitra_id) REFERENCES users(id),
  FOREIGN KEY (service_id) REFERENCES services(id),
  FOREIGN KEY (sub_service_id) REFERENCES sub_services(id)
);

-- +migrate Down
DROP TABLE order_transactions;
