-- +migrate Up
CREATE TABLE users (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    complete_name VARCHAR(255),
    email VARCHAR(255),
    phone_number VARCHAR(255),
    country_code VARCHAR(255),
    password TEXT,
    user_type ENUM('customer', 'mitra', 'admin') NOT NULL,
    user_level ENUM('no level', 'silver', 'gold', 'platinum') NOT NULL,
    color_code_level VARCHAR(10),
    user_rating DOUBLE NOT NULL,
    user_gender ENUM('male', 'female') NOT NULL,
    user_profile_image TEXT,
    is_logged_in ENUM('0', '1') DEFAULT '0',
    user_status ENUM('stay','waiting','picked up','on progress') DEFAULT 'stay',
    is_active ENUM('yes', 'no'),
    is_busy ENUM('yes', 'no') NOT NULL,
    is_document_completed ENUM('0', '1'),
    is_mitra_invited ENUM('0', '1') DEFAULT '0',
    is_mitra_accepted ENUM('0', '1') DEFAULT '0',
    is_mitra_rejected ENUM('0', '1'),
    is_mitra_activated ENUM('0', '1'),
    is_suspended ENUM('0', '1'),
    suspended_reason TEXT,
    violation_count INTEGER,
    violation_danger_count INTEGER,
    is_auto_bid ENUM('yes', 'no') NOT NULL,
    order_id_running INTEGER,
    sub_order_id_running INTEGER,
    customer_id_running INTEGER,
    service_id_running INTEGER,
    sub_service_id_running INTEGER,
    latitude VARCHAR(255) DEFAULT '',
    longitude VARCHAR(255) DEFAULT '',
    firebase_token TEXT,
    age VARCHAR(255) DEFAULT '0',
    ktp_number VARCHAR(16) DEFAULT '',
    date_of_birth VARCHAR(100) DEFAULT '',
    place_of_birth VARCHAR(100) DEFAULT '',
    ktp_image TEXT,
    kk_image TEXT,
    address TEXT,
    domisili_address VARCHAR(255) DEFAULT '',
    rt_rw VARCHAR(10) DEFAULT '',
    sub_district VARCHAR(100) DEFAULT '',
    district VARCHAR(100) DEFAULT '',
    province VARCHAR(100) DEFAULT '',
    city VARCHAR(100) DEFAULT '',
    postal_code VARCHAR(10) DEFAULT '',
    work_experience TEXT,
    user_tool TEXT,
    work_experience_cleaning ENUM('0', '1') DEFAULT '0',
    is_ex_golife ENUM('0', '1') DEFAULT '0',
    kind_of_mitra ENUM('Dengan Alat','Tanpa Alat') DEFAULT 'Tanpa Alat',
    work_experience_duration VARCHAR(100) DEFAULT '',
    emergency_contact_name VARCHAR(150) DEFAULT '',
    emergency_contact_relation VARCHAR(100) DEFAULT '',
    emergency_contact_country_code VARCHAR(20) DEFAULT '',
    emergency_contact_phone VARCHAR(20) DEFAULT '',
    cover_savings_book TEXT,
    time_invited DATETIME,
    place_invited VARCHAR(255),
    note_invited TEXT,
    today_order INT(11) DEFAULT 0,
    today_income BIGINT DEFAULT 0,
    total_order INTEGER DEFAULT 0,
    account_balance BIGINT DEFAULT 0.0,
    pay_pin TEXT,
    disbursement_pin TEXT,
    total_bills INTEGER DEFAULT 0,
    shared_prime INTEGER(5) DEFAULT 0,
    shared_base INTEGER(5) DEFAULT 0,
    shared_secret INTEGER(5) DEFAULT 0,
    private_key_pay_pin TEXT,
    public_key_pay_pin TEXT,
    private_key_disbursement_pin TEXT,
    rejection_count INTEGER DEFAULT 0,
    socket_id TEXT,
    browser_name VARCHAR(20),
    is_in_call ENUM('0', '1') DEFAULT '0',
    nonactivate_reason TEXT,
    activate_reason TEXT,
    registered_from_mobile ENUM('0', '1'),
    createdAt DATETIME NOT NULL,
    updatedAt DATETIME NOT NULL
);

-- +migrate Down
DROP TABLE users;
