CREATE TABLE transactions (
  id INT NOT NULL AUTO_INCREMENT,
  mitra_id VARCHAR(36),
  customer_id VARCHAR(36),
  order_id CHAR(36),
  sub_order_id INT,
  tool_id INT,
  tools_credits_id INT,
  sub_tools_id INT,
  refund_id VARCHAR(255),
  user_type ENUM('customer', 'mitra'),
  refund_amount INT,
  refund_type VARCHAR(255),
  topup_id VARCHAR(20),
  disbursement_id VARCHAR(100),
  order_id_transaction VARCHAR(10),
  external_id VARCHAR(100),
  idempotency_key VARCHAR(100),
  account_owner_name VARCHAR(255),
  bank_id INT,
  bank_name VARCHAR(255),
  bank_code VARCHAR(255),
  account_number VARCHAR(255),
  transaction_name VARCHAR(255),
  transaction_amount INT,
  transaction_amount_tax DOUBLE,
  transaction_fee INT,
  tax DOUBLE,
  last_amount INT,
  mobile_ewallet_url TEXT,
  timezone_code VARCHAR(255),
  transaction_type ENUM('transaction_out', 'transaction_in'),
  transaction_type_for VARCHAR(50),
  transaction_for ENUM('order', 'cicilan', 'disbursement', 'topup', 'other'),
  transaction_status ENUM('success', 'waiting', 'pending', 'failed'),
  failure_code VARCHAR(100),
  transaction_description TEXT,
  "createdAt" DATETIME NOT NULL,
  "updatedAt" DATETIME NOT NULL,
  PRIMARY KEY (id)
);