CREATE TABLE notifications (
  id CHAR(36) NOT NULL,
  customer_id VARCHAR(36),
  admin_id INT,
  mitra_id VARCHAR(36),
  order_id CHAR(36),
  sub_order_id INT,
  service_id INT,
  sub_service_id INT,
  transaction_id VARCHAR(36),
  user_type ENUM('customer', 'mitra', 'admin'),
  notification_type VARCHAR(255),
  notification_title VARCHAR(255),
  notification_message VARCHAR(255),
  notif_type ENUM('promo', 'order', 'topup', 'disbursement', 'status', 'news', 'other'),
  is_read ENUM('0', '1'),
  "createdAt" DATETIME NOT NULL,
  "updatedAt" DATETIME NOT NULL,
  PRIMARY KEY (id)
);