CREATE TABLE order_offers (
  id INT NOT NULL AUTO_INCREMENT,
  temp_id VARCHAR(255),
  order_id CHAR(36) NOT NULL,
  customer_id VARCHAR(36),
  mitra_id VARCHAR(36),
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);