-- deploy/seed.sql
-- ─────────────────────────────────────────────────────────────────────────────
-- Run AFTER the application performs GORM AutoMigrate (i.e. after the app has
-- started at least once and created all tables).
--
-- Idempotent: safe to run multiple times.
--
-- Executed automatically by deploy.sh after health check passes.
-- ─────────────────────────────────────────────────────────────────────────────

-- ════════════════════════════════════════════════════════════════════════════
-- 0. Seed users
-- ════════════════════════════════════════════════════════════════════════════

INSERT INTO users (id, complete_name, email, password, country_code, phone_number, user_type, color_code_level)
VALUES (
  '013a8111-0671-46a2-bd79-5ba869dbe07f',
  'naufal daffa',
  'naufalrachmat91@gmail.com',
  '$2a$10$Xg7hHRyA8Rw.Vdx2YunBOOLmVLcH9hsCMf4wec7be3B7W/n96xOS6',
  '+62',
  '+6285712356777',
  'superadmin',
  '#808080'
)
ON CONFLICT (id) DO NOTHING;

-- ════════════════════════════════════════════════════════════════════════════
-- 1. PostGIS extension
-- ════════════════════════════════════════════════════════════════════════════

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ════════════════════════════════════════════════════════════════════════════
-- 2. (no-op) Column types are managed by GORM AutoMigrate.
--    latitude/longitude are varchar(255) by design (model stores string).
--    Do NOT alter type here — GORM would revert it on the next deploy.
-- ════════════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════════
-- 3. geom generated column
--    Drop old non-generated column first (if any), then add as STORED generated.
--    CASE guard prevents error when longitude/latitude are NULL.
-- ════════════════════════════════════════════════════════════════════════════

DO $$
BEGIN
  -- Drop old manually-managed geom column (attgenerated = '' means not generated)
  IF EXISTS (
    SELECT 1 FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    WHERE c.relname = 'users' AND a.attname = 'geom'
      AND a.attnum > 0 AND NOT a.attisdropped
      AND a.attgenerated <> 's'
  ) THEN
    ALTER TABLE users DROP COLUMN geom;
  END IF;

  -- Add as STORED generated column if it doesn't exist yet
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    WHERE c.relname = 'users' AND a.attname = 'geom'
      AND a.attnum > 0 AND NOT a.attisdropped
  ) THEN
    ALTER TABLE users
      ADD COLUMN geom geography(Point, 4326)
      GENERATED ALWAYS AS (
        CASE
          WHEN longitude IS NOT NULL AND latitude IS NOT NULL
            AND longitude <> 0 AND latitude <> 0
            THEN ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography
        END
      ) STORED;
  END IF;
END $$;

-- ════════════════════════════════════════════════════════════════════════════
-- 4. Spatial index
-- ════════════════════════════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_users_geom ON users USING GIST(geom);

-- ════════════════════════════════════════════════════════════════════════════
-- 5. Partial composite index for active mitra search
-- ════════════════════════════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_users_mitra_active
  ON users(user_gender, is_auto_bid, account_balance)
  WHERE user_type = 'mitra'
    AND is_logged_in = '1'
    AND is_active = 'yes'
    AND is_busy = 'no'
    AND is_suspended = '0';


-- ════════════════════════════════════════════════════════════════════════════
-- 2. Seed: bank_lists
--    id, created_at, updated_at → generated by the database
--    Guard: skip rows whose `code` already exists
-- ════════════════════════════════════════════════════════════════════════════

INSERT INTO bank_lists (bank_image, name, code, disbursement_code, method_type, can_topup, can_disbursement, min_topup, min_disbursement, topup_fee, disbursement_fee, is_percentage, tutorial)
SELECT v.bank_image, v.name, v.code, v.disbursement_code, v.method_type,
       v.can_topup, v.can_disbursement, v.min_topup, v.min_disbursement,
       v.topup_fee, v.disbursement_fee, v.is_percentage, v.tutorial
FROM (VALUES
  ('/payments/BANK_IMG_2026-05-09_10-26-10_icon_mandiri.png', 'Bank Mandiri',                   'mandiri',  'MANDIRI',  'bank', '1', '1', 10000, NULL,  2775.0, NULL,   NULL, NULL),
  ('/bank_images/logo_bank_bri_cropped.png',                  'Bank Rakyat Indonesia',           'bri',      'BRI',      'bank', '1', '1', 10000, NULL,  2775.0, NULL,   NULL, NULL),
  ('/bank_images/logo_bank_bni_cropped.png',                  'BNI (Bank Negara Indonesia)',     'bni',      'BNI',      'bank', '1', '1', 11000, NULL,  2775.0, NULL,   NULL, NULL),
  ('/payments/BANK_IMG_2026-05-09_10-25-50_icon_bca.png',     'Bank Central Asia',               'bca',      'BCA',      'bank', '1', '1', 10000, 10000, 5000.0, 2775.0, NULL, NULL),
  ('/bank_images/logo_bank_bsi_cropped.png',                  'BSI (Bank Syariah Indonesia)',    'bsm',      'BSI',      'bank', '1', '1', 10000, NULL,  2775.0, NULL,   NULL, NULL),
  ('/bank_images/logo_bank_cimb_cropped.png',                 'CIMB Niaga Syariah (UUS)',        'cimb',     'CIMB_UUS', 'bank', '1', '1', 10000, NULL,  2775.0, NULL,   NULL, NULL),
  ('/bank_images/logo_bank_muamalat_cropped.png',             'Muamalat',                        'muamalat', 'MUAMALAT', 'bank', '1', '1', 10000, NULL,  2775.0, NULL,   NULL, NULL),
  ('/bank_images/logo_bank_permata_cropped.png',              'Bank Permata',                    'permata',  'PERMATA',  'bank', '1', '1', 10000, NULL,  2775.0, NULL,   NULL, NULL),
  ('/bank_images/logo_bank_maybank_cropped.png',              'Maybank Indonesia',               'bii',      'MAYBANK',  'bank', '1', '1', 10000, NULL,  2775.0, NULL,   NULL, NULL),
  ('/bank_images/logo_bank_panin.png',                        'Panin Bank',                      'panin',    'PANIN',    'bank', '1', '1', 10000, NULL,  2775.0, NULL,   NULL, NULL),
  ('/bank_images/logo_bank_ocbc_cropped.png',                 'OCBC NISP',                       'ocbc',     'OCBC',     'bank', '1', '1', 10000, NULL,  2775.0, NULL,   NULL, NULL),
  ('/bank_images/logo_bank_citibank_cropped.png',             'Citibank',                        'citibank', 'CITIBANK', 'bank', '1', '1', 10000, NULL,  2775.0, NULL,   NULL, NULL)
) AS v(bank_image, name, code, disbursement_code, method_type, can_topup, can_disbursement, min_topup, min_disbursement, topup_fee, disbursement_fee, is_percentage, tutorial)
WHERE NOT EXISTS (
  SELECT 1 FROM bank_lists bl WHERE bl.code = v.code
);

-- ════════════════════════════════════════════════════════════════════════════
-- 3. Seed: payments
--    id, created_at, updated_at → generated by the database
--    Guard: skip rows whose `type` already exists
-- ════════════════════════════════════════════════════════════════════════════

INSERT INTO payments (icon, is_active, title, type, "desc")
SELECT v.icon, v.is_active, v.title, v.type, v.desc
FROM (VALUES
  ('/payments/ic_card.png',   '1', 'Virtual Account', 'virtual account', 'Gampang bayarnya'),
  ('/payments/ic_cash.png',   '1', 'Tunai',           'tunai',           'Uang pas ya'),
  ('/payments/ic_cash_2.png', '0', 'Saldo',           'balance',         'Saldo terpotong'),
  ('/payments/wallet.png',    '1', 'E-Wallet',        'ewallet',         'Pakai DANA, OVO, dll')
) AS v(icon, is_active, title, type, desc)
WHERE NOT EXISTS (
  SELECT 1 FROM payments p WHERE p.type = v.type
);

-- ════════════════════════════════════════════════════════════════════════════
-- 4. Seed: sub_payments
--    id, created_at, updated_at → generated by the database
--    payment_id resolved by looking up the parent payment type
--    Guard: skip rows whose `title_payment` already exists
-- ════════════════════════════════════════════════════════════════════════════

-- Virtual Account sub-payments
INSERT INTO sub_payments (payment_id, icon, title, title_payment, enabled, "desc")
SELECT p.id, v.icon, v.title, v.title_payment, v.enabled, v.desc
FROM payments p,
(VALUES
  ('/payments/SUB_PAY_IMG_2026-05-09_09-54-37_icon_bca.png',     'BCA Virtual Account',     'BCA',     '1', 'BCA VA'),
  ('/payments/SUB_PAY_IMG_2026-05-09_09-48-52_icon_mandiri.png', 'Mandiri Virtual Account', 'MANDIRI', '1', 'Mandiri VA')
) AS v(icon, title, title_payment, enabled, desc)
WHERE p.type = 'virtual account'
  AND NOT EXISTS (
    SELECT 1 FROM sub_payments sp WHERE sp.title_payment = v.title_payment
  );

-- Tunai sub-payment
INSERT INTO sub_payments (payment_id, icon, title, title_payment, enabled, "desc")
SELECT p.id, '/payments/SUB_PAY_IMG_2026-05-09_10-41-57_icon_tunai.png', 'Tunai', 'TUNAI', '1', 'TUNAI'
FROM payments p
WHERE p.type = 'tunai'
  AND NOT EXISTS (
    SELECT 1 FROM sub_payments sp WHERE sp.title_payment = 'TUNAI'
  );

-- Saldo sub-payment
INSERT INTO sub_payments (payment_id, icon, title, title_payment, enabled, "desc")
SELECT p.id, '/sub_payments/saldo.png', 'Saldo Suberes', 'BALANCE', '1', 'Pakai saldo'
FROM payments p
WHERE p.type = 'balance'
  AND NOT EXISTS (
    SELECT 1 FROM sub_payments sp WHERE sp.title_payment = 'BALANCE'
  );

-- E-Wallet sub-payments
INSERT INTO sub_payments (payment_id, icon, title, title_payment, enabled, "desc")
SELECT p.id, v.icon, v.title, v.title_payment, v.enabled, v.desc
FROM payments p,
(VALUES
  ('/sub_payments/spay.png',                                  'ShopeePay', 'ID_SHOPEEPAY', '0', 'ShopeePay'),
  ('/payments/SUB_PAY_IMG_2026-05-09_10-52-50_icon_dana.png', 'DANA',      'ID_DANA',      '1', 'DANA')
) AS v(icon, title, title_payment, enabled, desc)
WHERE p.type = 'ewallet'
  AND NOT EXISTS (
    SELECT 1 FROM sub_payments sp WHERE sp.title_payment = v.title_payment
  );

-- ════════════════════════════════════════════════════════════════════════════
-- 5. Seed: superadmin user
--    Guard: skip jika user dengan id atau email ini sudah ada
-- ════════════════════════════════════════════════════════════════════════════

INSERT INTO users (
  id, complete_name, email, password,
  country_code, phone_number, user_type
)
SELECT
  '013a8111-0671-46a2-bd79-5ba869dbe07f',
  'naufal daffa',
  'naufalrachmat91@gmail.com',
  '$2a$10$Xg7hHRyA8Rw.Vdx2YunBOOLmVLcH9hsCMf4wec7be3B7W/n96xOS6',
  '+62',
  '+6285712356777',
  'superadmin'
WHERE NOT EXISTS (
  SELECT 1 FROM users
  WHERE id    = '013a8111-0671-46a2-bd79-5ba869dbe07f'
     OR email = 'naufalrachmat91@gmail.com'
);

-- ════════════════════════════════════════════════════════════════════════════
-- Summary
-- ════════════════════════════════════════════════════════════════════════════
DO $$
DECLARE
  bank_count    int;
  payment_count int;
  sub_pay_count int;
  user_count    int;
BEGIN
  SELECT count(*) INTO bank_count    FROM bank_lists;
  SELECT count(*) INTO payment_count FROM payments;
  SELECT count(*) INTO sub_pay_count FROM sub_payments;
  SELECT count(*) INTO user_count    FROM users WHERE user_type = 'superadmin';
  RAISE NOTICE 'Seed complete — bank_lists: %, payments: %, sub_payments: %, superadmin users: %',
               bank_count, payment_count, sub_pay_count, user_count;
END
$$;
